import { Router, type Router as RouterType } from "express";
import { requireAdmin, requireAuth } from "../../middleware/auth.ts";
import getAdminStats from "../controllers/admin-controllers/controller.admin.get_stats.ts";
import listPayments from "../controllers/admin-controllers/controller.admin.list_payments.ts";
import setUserBan from "../controllers/admin-controllers/controller.admin.set_user_ban.ts";
import adminListStudents from "../controllers/admin-controllers/controller.admin.list_students.ts";
import setStudentVerification from "../controllers/admin-controllers/controller.admin.set_student_verification.ts";
import listCancellationRequests from "../controllers/admin-controllers/controller.admin.list_cancellation_requests.ts";
import updateCancellationRequest from "../controllers/admin-controllers/controller.admin.update_cancellation_request.ts";
import searchCompanies from "../controllers/admin-controllers/controller.admin.search_companies.ts";
import createFreePostingGrant from "../controllers/admin-controllers/controller.admin.create_free_posting_grant.ts";
import listFreePostingGrants from "../controllers/admin-controllers/controller.admin.list_free_posting_grants.ts";
import revokeFreePostingGrant from "../controllers/admin-controllers/controller.admin.revoke_free_posting_grant.ts";
import createCoupon from "../controllers/admin-controllers/controller.admin.create_coupon.ts";
import listCoupons from "../controllers/admin-controllers/controller.admin.list_coupons.ts";
import revokeCoupon from "../controllers/admin-controllers/controller.admin.revoke_coupon.ts";
import createOffer from "../controllers/admin-controllers/controller.admin.create_offer.ts";
import listOffers from "../controllers/admin-controllers/controller.admin.list_offers.ts";
import revokeOffer from "../controllers/admin-controllers/controller.admin.revoke_offer.ts";

const router: RouterType = Router();
router.use(requireAuth);

router.get("/stats", requireAdmin, getAdminStats);
router.get("/payments", requireAdmin, listPayments);
router.get("/students", requireAdmin, adminListStudents);
router.post("/user/:id/ban", requireAdmin, setUserBan);
router.post("/student/:id/verify", requireAdmin, setStudentVerification);
router.get("/cancellation-requests", requireAdmin, listCancellationRequests);
router.patch("/cancellation-requests/:id", requireAdmin, updateCancellationRequest);
router.get("/coupons", requireAdmin, listCoupons);
router.post("/coupons", requireAdmin, createCoupon);
router.patch("/coupons/:id/revoke", requireAdmin, revokeCoupon);
router.get("/offers", requireAdmin, listOffers);
router.post("/offers", requireAdmin, createOffer);
router.patch("/offers/:id/revoke", requireAdmin, revokeOffer);
router.get("/company-search", requireAdmin, searchCompanies);
router.get("/allow-postings", requireAdmin, listFreePostingGrants);
router.post("/allow-postings", requireAdmin, createFreePostingGrant);
router.patch("/allow-postings/:id/revoke", requireAdmin, revokeFreePostingGrant);

export default router;
