// ISO 3166-1 friendly list, searchable. India default. Kept as a static
// list because we want consistent labels across employer profile + company
// + filters, and don't need translations or currency context yet.
export const COUNTRIES: readonly string[] = [
    "India",
    "United States",
    "United Kingdom",
    "Canada",
    "Australia",
    "Singapore",
    "United Arab Emirates",
    "Germany",
    "Netherlands",
    "Ireland",
    "France",
    "Spain",
    "Italy",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Switzerland",
    "Belgium",
    "Portugal",
    "Poland",
    "Czechia",
    "Austria",
    "New Zealand",
    "Japan",
    "South Korea",
    "China",
    "Hong Kong",
    "Taiwan",
    "Indonesia",
    "Malaysia",
    "Thailand",
    "Vietnam",
    "Philippines",
    "Sri Lanka",
    "Bangladesh",
    "Nepal",
    "Pakistan",
    "Bhutan",
    "Maldives",
    "Saudi Arabia",
    "Qatar",
    "Bahrain",
    "Kuwait",
    "Oman",
    "Israel",
    "Egypt",
    "South Africa",
    "Nigeria",
    "Kenya",
    "Ghana",
    "Brazil",
    "Argentina",
    "Mexico",
    "Chile",
    "Colombia",
    "Peru",
    "Other",
];

export const DEFAULT_COUNTRY = "India";
