export const INDUSTRIES: readonly string[] = [
    "Software / SaaS",
    "Fintech",
    "EdTech",
    "Healthtech",
    "E-commerce",
    "AI / ML",
    "Consumer Internet",
    "Gaming",
    "Cybersecurity",
    "Media / Entertainment",
    "Manufacturing",
    "Logistics",
    "Real Estate",
    "Energy / Cleantech",
    "Hospitality",
    "Retail",
    "Marketing / Advertising",
    "Consulting",
    "Government / Non-profit",
    "Other",
];
