import type { JobTitle } from "@/src/lib/api";

// Curated skill suggestions per job-title bucket. Free-typed entries the
// student/employer adds outside this catalog are still allowed and stored
// as raw tags — these just provide quick picks.
const BY_TITLE: Record<Exclude<JobTitle, "CUSTOM">, readonly string[]> = {
    AI: [
        "Python",
        "PyTorch",
        "TensorFlow",
        "Scikit-learn",
        "NumPy",
        "Pandas",
        "Hugging Face",
        "LangChain",
        "LLM Fine-Tuning",
        "Prompt Engineering",
        "Computer Vision",
        "NLP",
        "MLOps",
        "OpenAI API",
        "Vector Databases",
    ],
    BACKEND: [
        "Node.js",
        "Express",
        "NestJS",
        "Python",
        "Django",
        "FastAPI",
        "Java",
        "Spring Boot",
        "Go",
        "Ruby on Rails",
        "PostgreSQL",
        "MongoDB",
        "Redis",
        "Docker",
        "Kubernetes",
        "AWS",
        "GraphQL",
        "REST APIs",
    ],
    WEB: [
        "HTML",
        "CSS",
        "JavaScript",
        "TypeScript",
        "React",
        "Next.js",
        "Vue.js",
        "Angular",
        "Tailwind CSS",
        "Redux",
        "Node.js",
        "GraphQL",
        "Webpack",
        "Vite",
        "Sass",
    ],
    MOBILE: [
        "React Native",
        "Flutter",
        "Swift",
        "Kotlin",
        "Java (Android)",
        "Objective-C",
        "Dart",
        "Firebase",
        "Expo",
        "iOS",
        "Android",
    ],
    QA: [
        "Selenium",
        "Cypress",
        "Playwright",
        "Postman",
        "JIRA",
        "TestRail",
        "Appium",
        "Manual Testing",
        "Automation Testing",
        "Performance Testing",
    ],
    DESIGN: [
        "Figma",
        "Adobe XD",
        "Sketch",
        "Photoshop",
        "Illustrator",
        "InDesign",
        "After Effects",
        "Wireframing",
        "Prototyping",
        "User Research",
        "Design Systems",
        "Typography",
    ],
    PRODUCT: [
        "Roadmapping",
        "User Research",
        "JIRA",
        "Notion",
        "Figma",
        "Analytics",
        "SQL",
        "A/B Testing",
        "Stakeholder Management",
        "Agile",
        "Wireframing",
    ],
    MARKETING: [
        "SEO",
        "SEM",
        "Google Ads",
        "Meta Ads",
        "Email Marketing",
        "Content Marketing",
        "Social Media",
        "Copywriting",
        "Google Analytics",
        "HubSpot",
        "Mailchimp",
    ],
    CONTENT: [
        "Copywriting",
        "Blogging",
        "Editing",
        "Proofreading",
        "SEO Writing",
        "Technical Writing",
        "Storytelling",
        "Research",
        "Social Media Captions",
        "Scriptwriting",
    ],
    SALES: [
        "Lead Generation",
        "Cold Calling",
        "CRM",
        "HubSpot",
        "Salesforce",
        "Negotiation",
        "Pitching",
        "Outreach",
        "Email Sequences",
        "LinkedIn Sales Navigator",
    ],
    DATA: [
        "Python",
        "SQL",
        "Pandas",
        "NumPy",
        "Excel",
        "Power BI",
        "Tableau",
        "Looker",
        "R",
        "Statistics",
        "Data Visualization",
        "Snowflake",
        "BigQuery",
    ],
    HR: [
        "Recruiting",
        "Sourcing",
        "Onboarding",
        "Employee Engagement",
        "HRIS",
        "ATS",
        "Payroll",
        "LinkedIn Recruiter",
        "Performance Reviews",
        "Policy Drafting",
    ],
};

const COMMON: readonly string[] = [
    "Communication",
    "Problem Solving",
    "Teamwork",
    "MS Excel",
    "Git",
    "English Proficiency",
];

export function skillSuggestions(
    jobTitle: JobTitle | null | undefined,
): string[] {
    if (!jobTitle || jobTitle === "CUSTOM") {
        return Array.from(
            new Set([
                ...Object.values(BY_TITLE).flat().slice(0, 60),
                ...COMMON,
            ]),
        );
    }
    return Array.from(new Set([...BY_TITLE[jobTitle], ...COMMON]));
}

export function allSkillSuggestions(): string[] {
    return Array.from(new Set([...Object.values(BY_TITLE).flat(), ...COMMON]));
}
