import type { JobTitle, WorkMode } from "@/src/lib/api";

export type ListingTemplate = {
    key: string;
    label: string;
    category: string;
    jobTitle: JobTitle | null;
    mode: WorkMode;
    title: string;
    description: string;
    responsibilities: string[];
    preferences: string[];
    perks: string[];
    skillTags: string[];
    screeningQuestions?: string[];
};

const COMMON_PERKS = [
    "Flexible hours",
    "Certificate on completion",
    "Letter of recommendation",
];

const COMMON_QUESTIONS = [
    "What recent project of yours would you most like to talk about?",
    "When can you start, and how many hours per week are you available?",
];

export const LISTING_TEMPLATES: ListingTemplate[] = [
    {
        key: "ai-developer",
        label: "AI Developer Internship",
        category: "Technical",
        jobTitle: "AI",
        mode: "REMOTE",
        title: "AI Developer Internship",
        description:
            "Build intelligent features using modern AI tools and integrate them into real-world applications solving automation and productivity challenges.\n\n• Build AI-powered applications or features\n• Use Python, APIs, and AI libraries\n• Solve real-world automation problems\n• Learn model integration workflows\n• Work on cutting-edge technologies",
        responsibilities: [
            "Develop AI-powered features and tools",
            "Integrate APIs into applications",
            "Test and improve model outputs",
            "Collaborate with developers on implementation",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Python",
            "Machine Learning Basics",
            "API Integration",
            "Data Handling",
            "Problem Solving",
            "Git",
            "REST APIs",
            "Prompt Engineering",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "backend-developer",
        label: "Backend Developer Internship",
        category: "Technical",
        jobTitle: "BACKEND",
        mode: "REMOTE",
        title: "Backend Developer Internship",
        description:
            "Design scalable backend systems and APIs that power applications and securely manage user data and application workflows.\n\n• Build secure backend APIs\n• Use databases and server technologies\n• Solve data handling challenges\n• Learn scalable architecture patterns\n• Work on production-level systems",
        responsibilities: [
            "Develop RESTful APIs for applications",
            "Design database schemas and queries",
            "Implement authentication systems",
            "Debug backend performance issues",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Node.js",
            "Express.js",
            "REST APIs",
            "Database Design",
            "MongoDB",
            "SQL",
            "Authentication",
            "Git",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "web-app-developer",
        label: "Web App Developer Internship",
        category: "Technical",
        jobTitle: "WEB",
        mode: "REMOTE",
        title: "Web App Developer Internship",
        description:
            "Create responsive web applications that deliver seamless user experiences and solve real-world problems across modern browsers.\n\n• Build dynamic web applications\n• Use frontend and API technologies\n• Solve UI and workflow challenges\n• Learn full-stack development basics\n• Work on production-ready interfaces",
        responsibilities: [
            "Develop responsive web pages and components",
            "Integrate APIs into frontend systems",
            "Debug UI and functional issues",
            "Optimize application performance",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "HTML",
            "CSS",
            "JavaScript",
            "React",
            "API Integration",
            "Git",
            "Responsive Design",
            "Performance Optimization",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "mobile-app-developer",
        label: "Mobile App Developer Internship",
        category: "Technical",
        jobTitle: "MOBILE",
        mode: "REMOTE",
        title: "Mobile App Developer Internship",
        description:
            "Build mobile applications that deliver smooth user experiences and solve everyday user problems on modern mobile platforms.\n\n• Build functional mobile apps\n• Use mobile frameworks and APIs\n• Solve performance challenges\n• Learn mobile architecture basics\n• Work on user-facing applications",
        responsibilities: [
            "Develop mobile UI components",
            "Integrate APIs into mobile apps",
            "Debug mobile performance issues",
            "Test applications on devices",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Flutter",
            "Kotlin",
            "React Native",
            "Mobile UI Design",
            "API Integration",
            "Git",
            "State Management",
            "Performance Optimization",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "ui-ux-designer",
        label: "UI/UX Designer Internship",
        category: "Design & Product",
        jobTitle: "DESIGN",
        mode: "REMOTE",
        title: "UI/UX Designer Internship",
        description:
            "Design intuitive user interfaces that improve usability and enhance the overall user experience across digital platforms.\n\n• Create engaging UI layouts\n• Use design tools and prototyping\n• Solve usability challenges\n• Learn UX workflows\n• Work on real product interfaces",
        responsibilities: [
            "Design wireframes and prototypes",
            "Create consistent UI components",
            "Improve usability based on feedback",
            "Collaborate with developers on designs",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Figma",
            "UI Design",
            "UX Principles",
            "Wireframing",
            "Prototyping",
            "User Research",
            "Design Systems",
            "Usability Testing",
        ],
        screeningQuestions: [
            "Share a link to your portfolio.",
            ...COMMON_QUESTIONS,
        ],
    },
    {
        key: "qa-engineer",
        label: "QA Engineer Internship",
        category: "Technical",
        jobTitle: "QA",
        mode: "REMOTE",
        title: "QA Engineer Internship",
        description:
            "Ensure software quality by testing applications and identifying bugs that impact performance and user experience.\n\n• Test applications thoroughly\n• Use testing tools and methods\n• Solve reliability issues\n• Learn testing workflows\n• Improve software stability",
        responsibilities: [
            "Execute manual test cases",
            "Identify and report bugs clearly",
            "Verify fixes and retest features",
            "Maintain testing documentation",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Manual Testing",
            "Bug Reporting",
            "Test Cases",
            "Debugging",
            "Quality Assurance",
            "Documentation",
            "Regression Testing",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "product-manager",
        label: "Product Manager Internship",
        category: "Design & Product",
        jobTitle: "PRODUCT",
        mode: "REMOTE",
        title: "Product Manager Internship",
        description:
            "Plan product features and coordinate development efforts to ensure timely delivery of high-quality digital products.\n\n• Define product requirements\n• Use planning tools and workflows\n• Solve coordination challenges\n• Learn product lifecycle basics\n• Lead real product execution",
        responsibilities: [
            "Define feature requirements and tasks",
            "Track development progress regularly",
            "Coordinate communication between teams",
            "Maintain project documentation",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Product Planning",
            "Communication",
            "Task Management",
            "Leadership",
            "Documentation",
            "Agile Basics",
            "Requirement Analysis",
        ],
        screeningQuestions: [
            "Walk us through a product decision you made and the trade-offs.",
            ...COMMON_QUESTIONS,
        ],
    },
    {
        key: "product-researcher",
        label: "Product Researcher Internship",
        category: "Design & Product",
        jobTitle: "RESEARCHER",
        mode: "REMOTE",
        title: "Product Researcher Internship",
        description:
            "Analyze user behavior and market trends to discover new product opportunities and improve feature effectiveness.\n\n• Conduct user research activities\n• Use data and research tools\n• Solve product discovery challenges\n• Learn research workflows\n• Support product innovation",
        responsibilities: [
            "Conduct research on market trends",
            "Analyze competitor products and features",
            "Document research findings clearly",
            "Suggest product improvement ideas",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Market Research",
            "Data Analysis",
            "User Research",
            "Documentation",
            "Competitor Analysis",
            "Trend Analysis",
            "Presentation Skills",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "marketing-specialist",
        label: "Marketing Specialist Internship",
        category: "Marketing & Content",
        jobTitle: "MARKETING",
        mode: "REMOTE",
        title: "Marketing Specialist Internship",
        description:
            "Promote products and increase user engagement using creative marketing strategies across digital platforms.\n\n• Create marketing campaigns\n• Use social media tools\n• Solve user growth challenges\n• Learn digital marketing workflows\n• Drive product visibility",
        responsibilities: [
            "Create promotional campaign content",
            "Analyze marketing performance metrics",
            "Manage social media engagement",
            "Optimize marketing strategies",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Digital Marketing",
            "Social Media",
            "Content Promotion",
            "Analytics",
            "SEO Basics",
            "Campaign Planning",
            "Copywriting",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "content-writer",
        label: "Content Writer Internship",
        category: "Marketing & Content",
        jobTitle: "CONTENT",
        mode: "REMOTE",
        title: "Content Writer Internship",
        description:
            "Create clear and engaging written content that helps users understand products and improves communication effectiveness.\n\n• Write technical and general content\n• Use writing and editing tools\n• Solve communication challenges\n• Learn content workflows\n• Improve documentation quality",
        responsibilities: [
            "Write clear technical documentation",
            "Edit and proofread written content",
            "Research topics before writing",
            "Improve readability and clarity",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Writing",
            "Grammar",
            "Research",
            "Editing",
            "Proofreading",
            "SEO Basics",
            "Content Structuring",
            "Storytelling",
        ],
        screeningQuestions: [
            "Share 2 writing samples (links or PDFs).",
            ...COMMON_QUESTIONS,
        ],
    },
    {
        key: "video-editor",
        label: "Video Editor Internship",
        category: "Marketing & Content",
        jobTitle: "VIDEO",
        mode: "REMOTE",
        title: "Video Editor Internship",
        description:
            "Create engaging videos that visually communicate ideas and enhance product storytelling across digital platforms.\n\n• Edit engaging video content\n• Use editing software tools\n• Solve visual storytelling challenges\n• Learn video production workflows\n• Improve viewer engagement",
        responsibilities: [
            "Edit raw footage into final videos",
            "Add transitions and visual effects",
            "Optimize videos for platforms",
            "Maintain video quality standards",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Video Editing",
            "Premiere Pro",
            "CapCut",
            "Storytelling",
            "Transitions",
            "Audio Editing",
            "Color Correction",
            "Motion Graphics",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "sales-bd",
        label: "Sales / Business Development Internship",
        category: "Business & Analytics",
        jobTitle: "SALES",
        mode: "REMOTE",
        title: "Sales / Business Development Internship",
        description:
            "Help startups grow by generating leads, reaching out to potential customers, and supporting business growth activities.\n\n• Do startup outreach and lead generation\n• Use sales and CRM tools\n• Solve customer acquisition challenges\n• Learn startup growth workflows\n• Work closely with founders on growth",
        responsibilities: [
            "Research and identify potential leads",
            "Send outreach emails and messages",
            "Support sales and partnership activities",
            "Maintain lead tracking and CRM updates",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Communication",
            "Lead Generation",
            "Sales Basics",
            "Cold Outreach",
            "CRM Tools",
            "Negotiation",
            "Relationship Building",
            "Networking",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "social-media-manager",
        label: "Social Media Manager Internship",
        category: "Marketing & Content",
        jobTitle: "SOCIAL",
        mode: "REMOTE",
        title: "Social Media Manager Internship",
        description:
            "Manage and grow brand presence across social media platforms through consistent content creation and audience engagement.\n\n• Create and publish social media content\n• Use Instagram, LinkedIn, and other platforms\n• Solve audience engagement challenges\n• Learn content growth workflows\n• Improve startup online visibility",
        responsibilities: [
            "Create and schedule social media posts",
            "Manage audience engagement and replies",
            "Track content performance metrics",
            "Coordinate with marketing and design teams",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Social Media Management",
            "Instagram",
            "LinkedIn",
            "Content Creation",
            "Canva",
            "Copywriting",
            "Scheduling Tools",
            "Audience Engagement",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "data-analyst",
        label: "Data Analyst Internship",
        category: "Business & Analytics",
        jobTitle: "DATA",
        mode: "REMOTE",
        title: "Data Analyst Internship",
        description:
            "Analyze business and user data to help startups make smarter product, marketing, and growth decisions.\n\n• Analyze product and business metrics\n• Use spreadsheets and analytics tools\n• Solve data interpretation challenges\n• Learn reporting and dashboard workflows\n• Support data-driven decision making",
        responsibilities: [
            "Collect and clean business data",
            "Create reports and dashboards",
            "Analyze user behavior and trends",
            "Present insights to founders or teams",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Excel",
            "Google Sheets",
            "SQL",
            "Data Visualization",
            "Analytics",
            "Statistics Basics",
            "Dashboard Creation",
            "Python Basics",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
    {
        key: "human-resources",
        label: "Human Resources Internship",
        category: "Business & Analytics",
        jobTitle: "HR",
        mode: "REMOTE",
        title: "Human Resources Internship",
        description:
            "Support startup hiring, team coordination, and employee engagement activities while helping build strong workplace culture.\n\n• Assist with hiring and onboarding\n• Use communication and HR tools\n• Solve team coordination challenges\n• Learn recruitment and HR workflows\n• Support startup team growth",
        responsibilities: [
            "Screen candidate applications and resumes",
            "Coordinate interviews and onboarding processes",
            "Maintain employee records and documentation",
            "Support team communication and engagement activities",
        ],
        preferences: [],
        perks: COMMON_PERKS,
        skillTags: [
            "Communication",
            "Recruitment",
            "Interview Coordination",
            "People Management",
            "Organization",
            "Documentation",
            "HR Basics",
            "Relationship Building",
        ],
        screeningQuestions: COMMON_QUESTIONS,
    },
];

export const TEMPLATE_CATEGORIES = Array.from(
    new Set(LISTING_TEMPLATES.map((t) => t.category)),
);
