export const TOP_INDIAN_CITIES: readonly string[] = [
    "Ahmedabad",
    "Bengaluru",
    "Bhopal",
    "Bhubaneswar",
    "Chandigarh",
    "Chennai",
    "Coimbatore",
    "Dehradun",
    "Delhi",
    "Faridabad",
    "Goa",
    "Gurugram",
    "Guwahati",
    "Hyderabad",
    "Indore",
    "Jaipur",
    "Jodhpur",
    "Kanpur",
    "Kochi",
    "Kolkata",
    "Lucknow",
    "Ludhiana",
    "Madurai",
    "Mangaluru",
    "Mohali",
    "Mumbai",
    "Mysuru",
    "Nagpur",
    "Nashik",
    "Navi Mumbai",
    "Noida",
    "Patna",
    "Pune",
    "Raipur",
    "Ranchi",
    "Surat",
    "Thane",
    "Thiruvananthapuram",
    "Vadodara",
    "Varanasi",
    "Vijayawada",
    "Visakhapatnam",
];

export const OTHER_CITY_SENTINEL = "Other";
